# Generated by Django 4.0.6 on 2022-10-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_image_alter_product_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_front',
            field=models.ImageField(default='shop/noImageProduct.png', upload_to='shop/None/front/'),
        ),
    ]
