# Generated by Django 4.0.6 on 2022-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_image_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_back',
            field=models.ImageField(default='shop/noImageProduct.png', upload_to='shop/None/back/'),
        ),
    ]
