# Generated by Django 4.0.6 on 2022-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_back',
            field=models.ImageField(default='shop/noImageProduct.png', upload_to='shop/<django.db.models.fields.related.ForeignKey>/back/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_front',
            field=models.ImageField(default='shop/noImageProduct.png', upload_to='shop/<django.db.models.fields.related.ForeignKey>/front/'),
        ),
    ]
